#!/bin/bash


if [ ! -t 0 ]; then
  exec </dev/tty
fi

set -e

rm -rf "$HOME/wildberries-extras"

cd "$HOME" || exit 1
git clone --depth 1 https://github.com/howtoedittv/wildberries-extras.git || {
  echo "git clone failed"
  exit 1
}

while true; do
  echo
  echo "choose config to install"
  echo "1) DankMaterialShell"
  echo "2) foot"
  echo "3) vivaldi"
  echo "q) Quit the script"

  read -rp "Enter your choice: " CHOICE

  case "$CHOICE" in
  1)
    mkdir -p ~/.config/DankMaterialShell/themes/
    mv ~/wildberries-extras/com.wildberries.style.dms/ \
       ~/.config/DankMaterialShell/themes/wildberries || echo "move failed"
    echo "moved to ~/.config/DankMaterialShell/themes/wildberries. please open settings in dms go to themes and apply the json  file in the mentiond directory"
    ;;

  2)
    echo "Installing fonts (may ask for sudo)..."
    sudo mv ~/wildberries-extras/com.wildberries.style.foot/maplemono/ /usr/share/fonts/ || echo "font move failed"
    fc-cache -v || echo "fc-cache failed"

    mkdir -p ~/.config/foot/
    mv ~/wildberries-extras/com.wildberries.style.foot/foot.ini ~/.config/foot/ || echo "foot config move failed"

    echo "Restart foot to apply"
    ;;

  3)
    echo "Import theme from:"
    echo "~/wildberries-extras/com.wildberries.style.vivaldi"
    ;;

  q)
    echo "Exiting script."
    exit 0
    ;;

  *)
    echo "Invalid choice, try again."
    ;;
  esac
done
